[project]
name = "egyptian-trainer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11,<3.13"
dependencies = [
    "django>=5.0",
    "google-genai>=2.19.0",
    "gtts>=2.5.4",
    "librosa>=0.11.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.3",
    "django-admin-sortable2>=2.3.1",
    "gradio-client>=2.6.1",
]

[tool.uv]
override-dependencies = [
    "transformers @ git+https://github.com/huggingface/transformers.git",
]
