# Generated by Django 5.2.17 on 2026-08-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpair',
            name='conjugation_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordpair',
            name='root_letters',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='wordpair',
            name='word_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
