# Generated by Django 5.2.17 on 2026-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_wordpair_conjugation_info_wordpair_root_letters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='median_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
