# Generated by Django 5.2.17 on 2026-08-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_userprogress_median_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpair',
            name='root_letters',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wordpair',
            name='word_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
