# Generated by Django 5.2.17 on 2026-08-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_wordpair_root_letters_alter_wordpair_word_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='help_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.userprogress'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_input',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='arabic_script',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='arabizi',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='german_sentence',
            field=models.CharField(max_length=500),
        ),
    ]
