# Generated by Django 5.2.17 on 2026-08-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_attempt_progress_alter_attempt_user_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='help_info',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.userprogress'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_input',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='arabic_script',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='arabizi',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='german_sentence',
            field=models.CharField(max_length=500),
        ),
    ]
