# Generated by Django 5.2.17 on 2026-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_remove_phrase_help_info_alter_attempt_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='help_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
