# Generated by Django 5.2.17 on 2026-08-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_phrase_help_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='phrase_audio/'),
        ),
    ]
