# Generated by Django 5.2.17 on 2026-08-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_lernweg_level_phrase_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='phrase',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
